-- sql/schema.sql
BEGIN;

CREATE SCHEMA IF NOT EXISTS market_etl;


-- Assets
DROP TABLE IF EXISTS market_etl.assets cascade;
CREATE TABLE IF NOT EXISTS market_etl.assets (
    asset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol     TEXT NOT NULL UNIQUE,
    name       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- Markets
DROP TABLE IF EXISTS market_etl.markets cascade;
CREATE TABLE IF NOT EXISTS market_etl.markets (
    market_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange       TEXT NOT NULL DEFAULT 'binance',
    base_asset_id  BIGINT NOT NULL REFERENCES market_etl.assets(asset_id),
    quote_asset_id BIGINT NOT NULL REFERENCES market_etl.assets(asset_id),
    market_symbol  TEXT NOT NULL UNIQUE,
    status         TEXT NOT NULL DEFAULT 'active',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE INDEX IF NOT EXISTS idx_markets_base_quote
ON market_etl.markets (base_asset_id, quote_asset_id);


-- Candles (partitioned by open_time)
DROP TABLE IF EXISTS market_etl.candles cascade;
CREATE TABLE IF NOT EXISTS market_etl.candles (
    market_id              BIGINT NOT NULL REFERENCES market_etl.markets(market_id),
    interval               TEXT NOT NULL,
    open_time              TIMESTAMPTZ NOT NULL,
    close_time             TIMESTAMPTZ NOT NULL,
    open_price             NUMERIC(24,10) NOT NULL,
    high_price             NUMERIC(24,10) NOT NULL,
    low_price              NUMERIC(24,10) NOT NULL,
    close_price            NUMERIC(24,10) NOT NULL,
    volume                 NUMERIC(28,10) NOT NULL,
    quote_volume           NUMERIC(28,10),
    trade_count            BIGINT,
    taker_buy_base_volume  NUMERIC(28,10),
    taker_buy_quote_volume NUMERIC(28,10),
    inserted_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (market_id, interval, open_time)
) PARTITION BY RANGE (open_time);


DO $$
DECLARE
    d DATE := DATE '2025-05-01';
    last_month DATE := date_trunc('month', current_date)::date;
    part_name TEXT;
BEGIN
    WHILE d <= last_month LOOP
        part_name := format('candles_%s', to_char(d, 'YYYY_MM'));
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS market_etl.%I PARTITION OF market_etl.candles
            FOR VALUES FROM (%L) TO (%L);',
            part_name,
            (d::timestamp at time zone 'UTC'),
            ((d + INTERVAL '1 month')::timestamp at time zone 'UTC')
        );
        d := (d + INTERVAL '1 month')::date;
    END LOOP;
END $$;


CREATE INDEX IF NOT EXISTS idx_candles_market_time
ON market_etl.candles (market_id, open_time DESC);


-- Trades (partitioned by trade_time)
DROP TABLE IF EXISTS market_etl.trades cascade;
CREATE TABLE IF NOT EXISTS market_etl.trades (
    market_id      BIGINT NOT NULL REFERENCES market_etl.markets(market_id),
    trade_id       BIGINT NOT NULL,
    trade_time     TIMESTAMPTZ NOT NULL,
    price          NUMERIC(24,10) NOT NULL,
    qty            NUMERIC(28,10) NOT NULL,
    quote_qty      NUMERIC(28,10),
    is_buyer_maker BOOLEAN,
    inserted_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (market_id, trade_id, trade_time)
) PARTITION BY RANGE (trade_time);


DO $$
DECLARE
    d DATE := DATE '2025-05-01';
    last_month DATE := date_trunc('month', current_date)::date;
    part_name TEXT;
BEGIN
    WHILE d <= last_month LOOP
        part_name := format('trades_%s', to_char(d, 'YYYY_MM'));
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS market_etl.%I PARTITION OF market_etl.trades
            FOR VALUES FROM (%L) TO (%L);',
            part_name,
            (d::timestamp at time zone 'UTC'),
            ((d + INTERVAL '1 month')::timestamp at time zone 'UTC')
        );
        d := (d + INTERVAL '1 month')::date;
    END LOOP;
END $$;


CREATE INDEX IF NOT EXISTS idx_trades_market_time
ON market_etl.trades (market_id, trade_time DESC);


-- 24h ticker snapshots (daily)
DROP TABLE IF EXISTS market_etl.tickers_24h cascade;
CREATE TABLE IF NOT EXISTS market_etl.tickers_24h (
    market_id            BIGINT NOT NULL REFERENCES market_etl.markets(market_id),
    snapshot_date        DATE NOT NULL,
    price_change         NUMERIC(24,10),
    price_change_percent NUMERIC(18,10),
    weighted_avg_price   NUMERIC(24,10),
    prev_close_price     NUMERIC(24,10),
    last_price           NUMERIC(24,10),
    last_qty             NUMERIC(28,10),
    bid_price            NUMERIC(24,10),
    bid_qty              NUMERIC(28,10),
    ask_price            NUMERIC(24,10),
    ask_qty              NUMERIC(28,10),
    open_price           NUMERIC(24,10),
    high_price           NUMERIC(24,10),
    low_price            NUMERIC(24,10),
    volume               NUMERIC(28,10),
    quote_volume         NUMERIC(28,10),
    open_time            TIMESTAMPTZ,
    close_time           TIMESTAMPTZ,
    first_id             BIGINT,
    last_id              BIGINT,
    count                BIGINT,
    inserted_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (market_id, snapshot_date)
);


COMMIT;
